mkdir allgemeineliter00jahrgoog
mv allgemeineliter00jahrgoog*.txt allgemeineliter00jahrgoog/
mkdir allgemeineliter00schugoog
mv allgemeineliter00schugoog*.txt allgemeineliter00schugoog/
mkdir allgemeineliter01goog
mv allgemeineliter01goog*.txt allgemeineliter01goog/
mkdir allgemeineliter05jahrgoog
mv allgemeineliter05jahrgoog*.txt allgemeineliter05jahrgoog/
mkdir allgemeineliter10unkngoog
mv allgemeineliter10unkngoog*.txt allgemeineliter10unkngoog/
mkdir allgemeineliter115unkngoog
mv allgemeineliter115unkngoog*.txt allgemeineliter115unkngoog/
mkdir allgemeineliter136unkngoog
mv allgemeineliter136unkngoog*.txt allgemeineliter136unkngoog/
mkdir allgemeineliter13jahrgoog
mv allgemeineliter13jahrgoog*.txt allgemeineliter13jahrgoog/
mkdir allgemeineliter13unkngoog
mv allgemeineliter13unkngoog*.txt allgemeineliter13unkngoog/
mkdir allgemeineliter152unkngoog
mv allgemeineliter152unkngoog*.txt allgemeineliter152unkngoog/
mkdir allgemeineliter15jahrgoog
mv allgemeineliter15jahrgoog*.txt allgemeineliter15jahrgoog/
mkdir allgemeineliter161unkngoog
mv allgemeineliter161unkngoog*.txt allgemeineliter161unkngoog/
mkdir allgemeineliter162unkngoog
mv allgemeineliter162unkngoog*.txt allgemeineliter162unkngoog/
mkdir allgemeineliter163unkngoog
mv allgemeineliter163unkngoog*.txt allgemeineliter163unkngoog/
mkdir allgemeineliter16unkngoog
mv allgemeineliter16unkngoog*.txt allgemeineliter16unkngoog/
mkdir allgemeineliter170unkngoog
mv allgemeineliter170unkngoog*.txt allgemeineliter170unkngoog/
mkdir allgemeineliter181unkngoog
mv allgemeineliter181unkngoog*.txt allgemeineliter181unkngoog/
mkdir allgemeineliter183unkngoog
mv allgemeineliter183unkngoog*.txt allgemeineliter183unkngoog/
mkdir allgemeineliter186unkngoog
mv allgemeineliter186unkngoog*.txt allgemeineliter186unkngoog/
mkdir allgemeineliter196unkngoog
mv allgemeineliter196unkngoog*.txt allgemeineliter196unkngoog/
mkdir allgemeineliter201unkngoog
mv allgemeineliter201unkngoog*.txt allgemeineliter201unkngoog/
mkdir allgemeineliter208unkngoog
mv allgemeineliter208unkngoog*.txt allgemeineliter208unkngoog/
mkdir allgemeineliter211unkngoog
mv allgemeineliter211unkngoog*.txt allgemeineliter211unkngoog/
mkdir allgemeineliter216unkngoog
mv allgemeineliter216unkngoog*.txt allgemeineliter216unkngoog/
mkdir allgemeineliter226unkngoog
mv allgemeineliter226unkngoog*.txt allgemeineliter226unkngoog/
mkdir allgemeineliter23unkngoog
mv allgemeineliter23unkngoog*.txt allgemeineliter23unkngoog/
mkdir allgemeineliter245unkngoog
mv allgemeineliter245unkngoog*.txt allgemeineliter245unkngoog/
mkdir allgemeineliter24unkngoog
mv allgemeineliter24unkngoog*.txt allgemeineliter24unkngoog/
mkdir allgemeineliter253unkngoog
mv allgemeineliter253unkngoog*.txt allgemeineliter253unkngoog/
mkdir allgemeineliter262unkngoog
mv allgemeineliter262unkngoog*.txt allgemeineliter262unkngoog/
mkdir allgemeineliter276unkngoog
mv allgemeineliter276unkngoog*.txt allgemeineliter276unkngoog/
mkdir allgemeineliter297unkngoog
mv allgemeineliter297unkngoog*.txt allgemeineliter297unkngoog/
mkdir allgemeineliter298unkngoog
mv allgemeineliter298unkngoog*.txt allgemeineliter298unkngoog/
mkdir allgemeineliter30unkngoog
mv allgemeineliter30unkngoog*.txt allgemeineliter30unkngoog/
mkdir allgemeineliter32unkngoog
mv allgemeineliter32unkngoog*.txt allgemeineliter32unkngoog/
mkdir allgemeineliter33unkngoog
mv allgemeineliter33unkngoog*.txt allgemeineliter33unkngoog/
mkdir allgemeineliter34unkngoog
mv allgemeineliter34unkngoog*.txt allgemeineliter34unkngoog/
mkdir allgemeineliter355unkngoog
mv allgemeineliter355unkngoog*.txt allgemeineliter355unkngoog/
mkdir allgemeineliter42unkngoog
mv allgemeineliter42unkngoog*.txt allgemeineliter42unkngoog/
mkdir allgemeineliter43unkngoog
mv allgemeineliter43unkngoog*.txt allgemeineliter43unkngoog/
mkdir allgemeineliter46unkngoog
mv allgemeineliter46unkngoog*.txt allgemeineliter46unkngoog/
mkdir allgemeineliter48unkngoog
mv allgemeineliter48unkngoog*.txt allgemeineliter48unkngoog/
mkdir allgemeineliter55unkngoog
mv allgemeineliter55unkngoog*.txt allgemeineliter55unkngoog/
mkdir allgemeineliter64unkngoog
mv allgemeineliter64unkngoog*.txt allgemeineliter64unkngoog/
mkdir allgemeineliter66unkngoog
mv allgemeineliter66unkngoog*.txt allgemeineliter66unkngoog/
mkdir allgemeineliter77unkngoog
mv allgemeineliter77unkngoog*.txt allgemeineliter77unkngoog/
mkdir allgemeineliter82unkngoog
mv allgemeineliter82unkngoog*.txt allgemeineliter82unkngoog/
mkdir allgemeineliter83unkngoog
mv allgemeineliter83unkngoog*.txt allgemeineliter83unkngoog/
mkdir allgemeineliter96unkngoog
mv allgemeineliter96unkngoog*.txt allgemeineliter96unkngoog/
mkdir allgemeinelitera1845unse
mv allgemeinelitera1845unse*.txt allgemeinelitera1845unse/
mkdir allgemeinelitera1847unse
mv allgemeinelitera1847unse*.txt allgemeinelitera1847unse/
mkdir bub_gb__ClRAAAAYAAJ
mv bub_gb__ClRAAAAYAAJ*.txt bub_gb__ClRAAAAYAAJ/
mkdir bub_gb_3tTjAAAAMAAJ
mv bub_gb_3tTjAAAAMAAJ*.txt bub_gb_3tTjAAAAMAAJ/
mkdir bub_gb_7R44AAAAMAAJ
mv bub_gb_7R44AAAAMAAJ*.txt bub_gb_7R44AAAAMAAJ/
mkdir bub_gb_aDI4AAAAMAAJ
mv bub_gb_aDI4AAAAMAAJ*.txt bub_gb_aDI4AAAAMAAJ/
mkdir bub_gb_BB04AAAAMAAJ
mv bub_gb_BB04AAAAMAAJ*.txt bub_gb_BB04AAAAMAAJ/
mkdir bub_gb_BdCEAAAAIAAJ
mv bub_gb_BdCEAAAAIAAJ*.txt bub_gb_BdCEAAAAIAAJ/
mkdir bub_gb_ByBRAAAAYAAJ
mv bub_gb_ByBRAAAAYAAJ*.txt bub_gb_ByBRAAAAYAAJ/
mkdir bub_gb_cCQ4AAAAMAAJ
mv bub_gb_cCQ4AAAAMAAJ*.txt bub_gb_cCQ4AAAAMAAJ/
mkdir bub_gb_Chg4AAAAMAAJ
mv bub_gb_Chg4AAAAMAAJ*.txt bub_gb_Chg4AAAAMAAJ/
mkdir bub_gb_cR44AAAAMAAJ
mv bub_gb_cR44AAAAMAAJ*.txt bub_gb_cR44AAAAMAAJ/
mkdir bub_gb_fCg4AAAAMAAJ
mv bub_gb_fCg4AAAAMAAJ*.txt bub_gb_fCg4AAAAMAAJ/
mkdir bub_gb_fSM4AAAAMAAJ
mv bub_gb_fSM4AAAAMAAJ*.txt bub_gb_fSM4AAAAMAAJ/
mkdir bub_gb_Fy9RAAAAYAAJ
mv bub_gb_Fy9RAAAAYAAJ*.txt bub_gb_Fy9RAAAAYAAJ/
mkdir bub_gb_gR5RAAAAYAAJ
mv bub_gb_gR5RAAAAYAAJ*.txt bub_gb_gR5RAAAAYAAJ/
mkdir bub_gb_Hig4AAAAMAAJ
mv bub_gb_Hig4AAAAMAAJ*.txt bub_gb_Hig4AAAAMAAJ/
mkdir bub_gb_-hk4AAAAMAAJ
mv bub_gb_-hk4AAAAMAAJ*.txt bub_gb_-hk4AAAAMAAJ/
mkdir bub_gb_lyFRAAAAYAAJ
mv bub_gb_lyFRAAAAYAAJ*.txt bub_gb_lyFRAAAAYAAJ/
mkdir bub_gb_MSlRAAAAYAAJ
mv bub_gb_MSlRAAAAYAAJ*.txt bub_gb_MSlRAAAAYAAJ/
mkdir bub_gb_M-XjAAAAMAAJ
mv bub_gb_M-XjAAAAMAAJ*.txt bub_gb_M-XjAAAAMAAJ/
mkdir bub_gb_mxs4AAAAMAAJ
mv bub_gb_mxs4AAAAMAAJ*.txt bub_gb_mxs4AAAAMAAJ/
mkdir bub_gb_NhI4AAAAMAAJ
mv bub_gb_NhI4AAAAMAAJ*.txt bub_gb_NhI4AAAAMAAJ/
mkdir bub_gb_nNXjAAAAMAAJ
mv bub_gb_nNXjAAAAMAAJ*.txt bub_gb_nNXjAAAAMAAJ/
mkdir bub_gb_NtXjAAAAMAAJ
mv bub_gb_NtXjAAAAMAAJ*.txt bub_gb_NtXjAAAAMAAJ/
mkdir bub_gb_ogs4AAAAMAAJ
mv bub_gb_ogs4AAAAMAAJ*.txt bub_gb_ogs4AAAAMAAJ/
mkdir bub_gb_ohI4AAAAMAAJ
mv bub_gb_ohI4AAAAMAAJ*.txt bub_gb_ohI4AAAAMAAJ/
mkdir bub_gb_PRU4AAAAMAAJ
mv bub_gb_PRU4AAAAMAAJ*.txt bub_gb_PRU4AAAAMAAJ/
mkdir bub_gb_Pww4AAAAMAAJ
mv bub_gb_Pww4AAAAMAAJ*.txt bub_gb_Pww4AAAAMAAJ/
mkdir bub_gb_Qiw4AAAAMAAJ
mv bub_gb_Qiw4AAAAMAAJ*.txt bub_gb_Qiw4AAAAMAAJ/
mkdir bub_gb_qsaEAAAAIAAJ
mv bub_gb_qsaEAAAAIAAJ*.txt bub_gb_qsaEAAAAIAAJ/
mkdir bub_gb_quXjAAAAMAAJ
mv bub_gb_quXjAAAAMAAJ*.txt bub_gb_quXjAAAAMAAJ/
mkdir bub_gb_rzA4AAAAMAAJ
mv bub_gb_rzA4AAAAMAAJ*.txt bub_gb_rzA4AAAAMAAJ/
mkdir bub_gb_s4crAAAAYAAJ
mv bub_gb_s4crAAAAYAAJ*.txt bub_gb_s4crAAAAYAAJ/
mkdir bub_gb_sBE4AAAAMAAJ
mv bub_gb_sBE4AAAAMAAJ*.txt bub_gb_sBE4AAAAMAAJ/
mkdir bub_gb_t9fjAAAAMAAJ
mv bub_gb_t9fjAAAAMAAJ*.txt bub_gb_t9fjAAAAMAAJ/
mkdir bub_gb_uhE4AAAAMAAJ
mv bub_gb_uhE4AAAAMAAJ*.txt bub_gb_uhE4AAAAMAAJ/
mkdir bub_gb_whY4AAAAMAAJ
mv bub_gb_whY4AAAAMAAJ*.txt bub_gb_whY4AAAAMAAJ/
mkdir bub_gb_wokFAAAAQAAJ
mv bub_gb_wokFAAAAQAAJ*.txt bub_gb_wokFAAAAQAAJ/
mkdir bub_gb_Wx04AAAAMAAJ
mv bub_gb_Wx04AAAAMAAJ*.txt bub_gb_Wx04AAAAMAAJ/
mkdir bub_gb_XdzjAAAAMAAJ
mv bub_gb_XdzjAAAAMAAJ*.txt bub_gb_XdzjAAAAMAAJ/
mkdir bub_gb_Yxg4AAAAMAAJ
mv bub_gb_Yxg4AAAAMAAJ*.txt bub_gb_Yxg4AAAAMAAJ/
mkdir bub_gb_zDQ4AAAAMAAJ
mv bub_gb_zDQ4AAAAMAAJ*.txt bub_gb_zDQ4AAAAMAAJ/
mkdir bub_gb_ZRs4AAAAMAAJ
mv bub_gb_ZRs4AAAAMAAJ*.txt bub_gb_ZRs4AAAAMAAJ/
mkdir bub_gb_ZTQ4AAAAMAAJ
mv bub_gb_ZTQ4AAAAMAAJ*.txt bub_gb_ZTQ4AAAAMAAJ/
mkdir bub_gb_ehw4AAAAMAAJ
mv bub_gb_ehw4AAAAMAAJ*.txt bub_gb_ehw4AAAAMAAJ/
mkdir bub_gb_f9bjAAAAMAAJ
mv bub_gb_f9bjAAAAMAAJ*.txt bub_gb_f9bjAAAAMAAJ/
mkdir allgemeineliter198unkngoog
mv allgemeineliter198unkngoog*.txt allgemeineliter198unkngoog/
mkdir allgemeineliter215unkngoog
mv allgemeineliter215unkngoog*.txt allgemeineliter215unkngoog/
mkdir bub_gb_cN7jAAAAMAAJ
mv bub_gb_cN7jAAAAMAAJ*.txt bub_gb_cN7jAAAAMAAJ/
mkdir bub_gb_cogFAAAAQAAJ
mv bub_gb_cogFAAAAQAAJ*.txt bub_gb_cogFAAAAQAAJ/
