wget https://archive.org/download/bub_gb_t9fjAAAAMAAJ/bub_gb_t9fjAAAAMAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter297unkngoog/allgemeineliter297unkngoog_jp2.zip &&
wget https://archive.org/download/bub_gb_MSlRAAAAYAAJ/bub_gb_MSlRAAAAYAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter152unkngoog/allgemeineliter152unkngoog_jp2.zip &&
wget https://archive.org/download/bub_gb_ogs4AAAAMAAJ/bub_gb_ogs4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_Pww4AAAAMAAJ/bub_gb_Pww4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_ByBRAAAAYAAJ/bub_gb_ByBRAAAAYAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter186unkngoog/allgemeineliter186unkngoog_jp2.zip &&
wget https://archive.org/download/bub_gb_XdzjAAAAMAAJ/bub_gb_XdzjAAAAMAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_sBE4AAAAMAAJ/bub_gb_sBE4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_NhI4AAAAMAAJ/bub_gb_NhI4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_lyFRAAAAYAAJ/bub_gb_lyFRAAAAYAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_M-XjAAAAMAAJ/bub_gb_M-XjAAAAMAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_quXjAAAAMAAJ/bub_gb_quXjAAAAMAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_uhE4AAAAMAAJ/bub_gb_uhE4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_ohI4AAAAMAAJ/bub_gb_ohI4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter183unkngoog/allgemeineliter183unkngoog_jp2.zip &&
wget https://archive.org/download/bub_gb_ZTQ4AAAAMAAJ/bub_gb_ZTQ4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_zDQ4AAAAMAAJ/bub_gb_zDQ4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter05jahrgoog/allgemeineliter05jahrgoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter00schugoog/allgemeineliter00schugoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter64unkngoog/allgemeineliter64unkngoog_jp2.zip &&
wget https://archive.org/download/bub_gb_whY4AAAAMAAJ/bub_gb_whY4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter298unkngoog/allgemeineliter298unkngoog_jp2.zip &&
wget https://archive.org/download/bub_gb_BdCEAAAAIAAJ/bub_gb_BdCEAAAAIAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_aDI4AAAAMAAJ/bub_gb_aDI4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter15jahrgoog/allgemeineliter15jahrgoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter262unkngoog/allgemeineliter262unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter216unkngoog/allgemeineliter216unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter276unkngoog/allgemeineliter276unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter161unkngoog/allgemeineliter161unkngoog_jp2.zip &&
wget https://archive.org/download/bub_gb_ZRs4AAAAMAAJ/bub_gb_ZRs4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter16unkngoog/allgemeineliter16unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter24unkngoog/allgemeineliter24unkngoog_jp2.zip &&
wget https://archive.org/download/bub_gb_BB04AAAAMAAJ/bub_gb_BB04AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_Wx04AAAAMAAJ/bub_gb_Wx04AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter13unkngoog/allgemeineliter13unkngoog_jp2.zip &&
wget https://archive.org/download/bub_gb_cR44AAAAMAAJ/bub_gb_cR44AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter208unkngoog/allgemeineliter208unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter162unkngoog/allgemeineliter162unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter43unkngoog/allgemeineliter43unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter01goog/allgemeineliter01goog_jp2.zip &&
wget https://archive.org/download/allgemeineliter181unkngoog/allgemeineliter181unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter66unkngoog/allgemeineliter66unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter211unkngoog/allgemeineliter211unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter48unkngoog/allgemeineliter48unkngoog_jp2.zip &&
wget https://archive.org/download/bub_gb_wokFAAAAQAAJ/bub_gb_wokFAAAAQAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_fSM4AAAAMAAJ/bub_gb_fSM4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_cCQ4AAAAMAAJ/bub_gb_cCQ4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_Hig4AAAAMAAJ/bub_gb_Hig4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_fCg4AAAAMAAJ/bub_gb_fCg4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter32unkngoog/allgemeineliter32unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter82unkngoog/allgemeineliter82unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter245unkngoog/allgemeineliter245unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter34unkngoog/allgemeineliter34unkngoog_jp2.zip &&
wget https://archive.org/download/bub_gb__ClRAAAAYAAJ/bub_gb__ClRAAAAYAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter170unkngoog/allgemeineliter170unkngoog_jp2.zip &&
wget https://archive.org/download/bub_gb_Qiw4AAAAMAAJ/bub_gb_Qiw4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter115unkngoog/allgemeineliter115unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter196unkngoog/allgemeineliter196unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter33unkngoog/allgemeineliter33unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter163unkngoog/allgemeineliter163unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter10unkngoog/allgemeineliter10unkngoog_jp2.zip &&
wget https://archive.org/download/bub_gb_PRU4AAAAMAAJ/bub_gb_PRU4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter96unkngoog/allgemeineliter96unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter55unkngoog/allgemeineliter55unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter83unkngoog/allgemeineliter83unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter226unkngoog/allgemeineliter226unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter355unkngoog/allgemeineliter355unkngoog_jp2.zip &&
wget https://archive.org/download/bub_gb_Chg4AAAAMAAJ/bub_gb_Chg4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_Yxg4AAAAMAAJ/bub_gb_Yxg4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter30unkngoog/allgemeineliter30unkngoog_jp2.zip &&
wget https://archive.org/download/bub_gb_rzA4AAAAMAAJ/bub_gb_rzA4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter13jahrgoog/allgemeineliter13jahrgoog_jp2.zip &&
wget https://archive.org/download/bub_gb_-hk4AAAAMAAJ/bub_gb_-hk4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter136unkngoog/allgemeineliter136unkngoog_jp2.zip &&
wget https://archive.org/download/bub_gb_mxs4AAAAMAAJ/bub_gb_mxs4AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter46unkngoog/allgemeineliter46unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter23unkngoog/allgemeineliter23unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter42unkngoog/allgemeineliter42unkngoog_jp2.zip &&
wget https://archive.org/download/bub_gb_7R44AAAAMAAJ/bub_gb_7R44AAAAMAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_qsaEAAAAIAAJ/bub_gb_qsaEAAAAIAAJ_jp2.zip &&
wget https://archive.org/download/bub_gb_Fy9RAAAAYAAJ/bub_gb_Fy9RAAAAYAAJ_jp2.zip &&
wget https://archive.org/download/allgemeinelitera1845unse/allgemeinelitera1845unse_jp2.zip &&
wget https://archive.org/download/bub_gb_s4crAAAAYAAJ/bub_gb_s4crAAAAYAAJ_jp2.zip &&
wget https://archive.org/download/allgemeineliter201unkngoog/allgemeineliter201unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter77unkngoog/allgemeineliter77unkngoog_jp2.zip &&
wget https://archive.org/download/allgemeineliter00jahrgoog/allgemeineliter00jahrgoog_jp2.zip &&
wget https://archive.org/download/allgemeinelitera1847unse/allgemeinelitera1847unse_jp2.zip &&
wget https://archive.org/download/allgemeineliter253unkngoog/allgemeineliter253unkngoog_jp2.zip &&
wget https://archive.org/download/bub_gb_gR5RAAAAYAAJ/bub_gb_gR5RAAAAYAAJ_jp2.zip
