import os
import random
import pandas as pd

df = pd.read_csv('bisher.tsv',sep='\t',encoding="utf-8",names=['year','volume','page','column','line','url','sentence'])

newdf = df.sample(n=10)

with open('google_script.txt','w',encoding='utf-8') as f:
	f.write('function createForm() {\n')

	f.write('\titem = \"')
	f.write('Einbildungskraft in der ALZ\";\n')
	f.write('\tvar form = FormApp.create(item)\n')
	f.write('\t\t.setTitle(item)\n')
	f.write('\t\t.setDescription(\"Willkommen bei unserem Projekt zur Semantik von Einbildungskraft in der \\"Allgemeine-Literatur-Zeitung\\"!\\n\\nVielen Dank, dass Sie uns dabei helfen, Textbelege zum Thema Einbildungskraft aus der Quelle \\"Allgemeine-Literatur-Zeitung\\" \\(1785–1849\\) anhand eines Kodiersystems auszuwerten. Das Ziel unseres Projektes ist die Rekonstruktion des Bedeutungswandels von Einbildungskraft um 1800 in unterschiedlichen Disziplinen anhand einer der verbreitetesten deutschsprachigen Zeitschriften der Epoche.\\n\\nSie bewerten insgesamt 400 Textbelege. Da es während der Bewertung nicht möglich ist, den aktuellen Stand zu speichern, werten Sie die Textbelege in 10er-Blöcken aus. Bitte bewerten Sie daher immer mindestens einen Block, also zehn Belege am Stück. Behalten Sie einen Überblick darüber, bei welchem Block Sie aufgehört haben. Alle Belege, die Sie bewerten, werden von weiteren Personen bewertet, um die Objektivität der Ergebnisse miteinander zu gewährleisten.\\n\\nZu jedem Textbeleg werden Ihnen Fragen zu folgenden Kategorien gestellt:\\n\\nBewertung: Wird das Wort \\"Einbildungskraft\\" in einem positiven, negativen oder neutralen Sinn verwendet? \\(positiv/negativ/neutral\\)\\n\\nInhalt: Wird es als Vermögen beschrieben, das etwas Neues hervorbringt oder als Vermögen, das etwas schon Bestehendes bloß im Bewusstsein wiederholt? \\(produktiv/reproduktiv\\)\\n\\nModus: Wird es als Vermögen beschrieben, das bewusst eingesetzt werden kann, oder als solches, das Wahrnehmungen und Handlungen begleitet? \\(aktiv/passiv\\)\\n\\nAdressaten: Wird es als Vermögen eines Individuums, einer Gruppe von Menschen oder als allgemeinmenschliche Eigenschaft beschrieben? \\(individuell/einige/allgemein\\)\\n\\nQuelle: Handelt es sich bei dem Textbeleg, um ein Zitat, um die Meinung einer weiteren Person, einen Titel oder um die Meinung des Autors bzw. der Autorin? \\(direktes Zitat/indirektes Zitat/Titel/Meinung\\)\\n\\nDistanz: Wird etwas mit Einbildungskraft beschrieben oder wird über Einbildungskraft gesprochen? \\(objektsprachlich/metasprachlich\\)\\n\\nDisziplin: Im Zusammenhang mit welcher Disziplin wird hier über Einbildungskraft gesprochen? \\(Ästhetik [Bildende Kunst, Literatur, Mythologie, Musik etc.]/Geschichte/Medizin/Naturwissenschaft [Geographie, Geologie, Chemie, Biologie etc.]/Pädagogik/Philosophie/Psychologie/Religion\\)\\n\\nWiderpruch: Liegt in dem Beleg ein Widerspruch vor?\\n\\nWissen des Raters: Haben Sie die Fragen mit Hilfe von Kontextwissen beantwortet, das über den Beleg hinausgeht, beantwortet oder haben Sie zur Beantwortung Kontextwissen hinzugezogen? \\(textimmanent/kontextuell\\)\\n\\nGesamtbewertung: Ist die Bewertung insgesamt schwierig gewesen?\\n\\nBei einigen Kategorien haben Sie die Möglichkeit, „beides“ zu markieren. Alle Kategorien bis auf \\"Widerspruch\\" und \\"Gesamtbewertung\\" müssen Sie markieren, um zum nächsten Textbeleg zu gelangen.\\n\\nWährend in der Kategorie „Disziplin“ Mehrfachnennungen möglich sind, müssen Sie die letzten beiden Kategorien nur ankreuzen, wenn sie auch zutreffen.\\n\\nWenn Sie bei der Beantwortung einzelner Fragen starke Schwierigkeiten haben und Sie keine Entscheidung über die Zuordnung treffen können, markieren Sie „Ich weiß es nicht“. Falls eine Kategorie schlicht nicht zutrifft, markieren Sie „trifft nicht zu“. Es kann sein, dass sich einige Belege erst dann erschließen, wenn Sie den argumentativen Kontext kennen. In den meisten Fällen ist ein Link zu der Quelle des Belegs vorhanden, mit dem Sie den Kontext des Belegs aufrufen können.\\n\\nSie werden merken, dass es Ihnen im Lauf des Bewertungsprozesses leichter fallen wird, die Belege zu intepretieren. Sie sollten versuchen auf ca. drei Minuten pro interpretierten Textbeleg zu kommen.\\n\\nZunächst folgt die beispielhafte Bewertung dreier Textbelege. Danach sind Sie gefragt : \\)\\n\\nWir bedanken uns jetzt schon einmal vielfach für die Mitarbeit an unserem Projekt!\\nTinghui Duan, Hendrick Heimböckel\")\n')
	f.write('\n')
	f.write('\tquestion1 = \"1. Wird das Wort \\"Einbildungskraft\\" in einem positiven, negativen oder neutralen Sinn verwendet?\";\n')
	f.write('\n')
	f.write('\tquestion2 = \"2. Wird es als Vermögen beschrieben, das etwas Neues hervorbringt \\(produktiv\\), oder als Vermögen, das etwas schon Bestehendes bloß im Bewusstsein wiederholt \\(reproduktiv\\)?\";\n')
	f.write('\n')
	f.write('\tquestion3 = \"3. Wird es als Vermögen beschrieben, das bewusst eingesetzt werden kann \\(aktiv\\), oder als solches, das Wahrnehmungen und Handlungen begleitet \\(passiv\\)?\";\n')
	f.write('\n')
	f.write('\tquestion4 = \"4. Wird es auf ein konkretes Individuum \\(individuell\\), auf eine Gruppe von Menschen \\(einige\\) bezogen oder als allgemeinmenschliches Vermögen \\(allgemein\\) beschrieben?\";\n')
	f.write('\n')
	f.write('\tquestion5 = \"5. Handelt es sich bei dem Textbeleg, in dem Einbildungskraft verwendet wird, um ein Zitat \\(direktes Zitat\\), um die Meinung einer weiteren Person \\(indirektes Zitat\\), den Titel einer Publikation \\(Titel\\) oder um die Meinung des Autors bzw. der Autorin \\(Meinung\\)?\";\n')
	f.write('\n')
	f.write('\tquestion6 = \"6. Wird etwas mit Einbildungskraft beschrieben \\(objektsprachlich\\) oder wird über Einbildungskraft gesprochen \\(metasprachlich\\)?\";\n')
	f.write('\n')
	f.write('\tquestion7 = \"7. Im Zusammenhang mit welcher Disziplin wird hier über Einbildungskraft gesprochen?\";\n')
	f.write('\n')
	f.write('\tquestion8 = \"8. Liegt in dem Beleg ein Widerspruch vor?\";\n')
	f.write('\n')
	f.write('\tquestion9 = \"9. Haben Sie die Fragen anhand des Beleges beantwortet \\(textimmanent\\) oder haben Sie zur Beantwortung Kontextwissen hinzugezogen \\(kontextuell\\)?\";\n')
	f.write('\n')
	f.write('\tquestion10 = \"10. Ist die Bewertung des Belegs insgesamt schwierig gewesen?\";\n')
	f.write('\n')
	#Beispiel 1
	f.write('\tvar classSection = form.addPageBreakItem()\n')
	f.write('\t\t.setTitle(\"Beispiel 1\")\n')
	f.write('\t\t.setHelpText(\"Textbeleg: \\"Die Dichtung Elyſium II. Th. 167. deren Eingang etwas weit vollkommneres erwarten lieſs, als die Fortſetzung leiſtet, läſst bey allen äuſsern Schein eines lebhaft erregten Gemüthes, die Einbildungskraft kalt und leer.\\"\\n\\nBewertung: positiv \\n--> Begründung: es wird aufgrund des Titels ein großartiger Text erwartet; doch wird die Einbildungskraft nicht bewegt, weshalb der Text gar nicht so großartig ist, wie der Titel es vermuten lässt\\n\\nInhalt: produktiv/reproduktiv \\n--> Begründung: es geht um die Vorstellungen während der Lektüre: einerseits werden in der Lektüre neue Bilder produziert, die andererseits wiederum nur durch die Worte im Text entstehen können\\n\\nModus: passiv\\n--> Begründung: die Einbildungskraft wird bei der Lektüre automatisch in Bewegung gesetzt\\n\\nAdressaten: einige \\n--> Begründung: es werden alle Rezipienten des Textes gemeint\\n\\nQuelle: Meinung \\n--> Begründung: der Autor spricht über einen Text \\n\\nDistanz: objektsprachlich \\n--> Begründung: es wird anhand von Einbildungskraft ein Text qualitativ bewertet \\n\\nWissen des Raters: textimmanent \\n--> Begründung: der Beleg wurde nicht anhand von Kontextwissen des Raters interpretiert\\n\\nDisziplin: Ästhetik \\n--> Begründung: es wird über Einbildungskraft im Kontext der Rezeption eines literarischen Textes geschrieben\")\n')
	#Beispiel 2
	f.write('\tvar classSection = form.addPageBreakItem()\n')
	f.write('\t\t.setTitle(\"Beispiel 2\")\n')
	f.write('\t\t.setHelpText(\"Textbeleg: \\"Die Einbildungskraft forme und bilde den Stoff der Vorſtellung; das Gefühlvermögen ertheile dem Begriffe Fülle und Wärme; die Phantaſie erhebe die allgemeinen Vernunftformeln zu Idealen.\\"\\n\\nBewertung: neutral\\n--> Begründung: die Funktion der Einbildungskraft wird beschrieben, ohne dass sie bewertet wird\\n\\nInhalt: produktiv \\n--> Begründung: die Einbildungskraft bringt eigene Vorstellungen hervor\\n\\nModus: passiv\\n--> Begründung: sie wird in diesem Abschnitt als autonom beschrieben\\n\\nAdressaten: allgemein\\n--> Begründung: es wird die allgemeinmenschliche Funktionsweise der Einbildungskraft beschrieben\\n\\nQuelle des Belegs: indirektes Zitat\\n--> Begründung: der Autor verwendet den Konjunktiv \\n\\nDistanz: metasprachlich\\n--> Begründung: es wird über die Funktionsweise der Einbildungskraft gesprochen \\n\\nDisziplin: Philosophie\\n--> Begründung: es wird über Einbildungskraft im Kontext der Rezeption eines literarischen Textes geschrieben\\n\\nQuelle der Bewertung: kontextuell\\n--> Begründung: hier geht es um anthropologische Vermögen, einem historischen philosophischen Denkmodell\")\n')
	#Beispiel 3
	f.write('\tvar classSection = form.addPageBreakItem()\n')
	f.write('\t\t.setTitle(\"Beispiel 3\")\n')
	f.write('\t\t.setHelpText(\"Textbeleg: \\"Hieraus folgt, ſagt Hr. Müller, daſs es eigentlich keine Gedächtniſskunſt giebt; allenfalls eine Erinnerungswiſſenſchaft, wobey eine Thätigkeit des Witzes, der Einbildungskraft, der Phantaſie und andre Geiſtesthätigkeiten gelegentlich einer ſchlechten Memorie einhelfen können..\\"\\n\\nBewertung: positiv\\n--> Begründung: Einbildungskraft ist dem Erinnern hilfreich\\n\\nInhalt: reproduktiv\\n--> Begründung: es geht um die Erinnerung von schon Erlebten mithilfe der Einbildungskraft\\n\\nModus: aktiv\\n--> Begründung: Einbildungskraft kann aktiv zum Erinnern eingesetzt werden\\n\\nAdressaten: allgemein\\n--> Begründung: es wird die allgemeinmenschliche Möglichkeit der Einbildungskraft beschrieben\\n\\nQuelle des Belegs: Zitat\\n--> Begründung: es wird die Meinung einer anderen Person direkt wiedergegeben\\n\\nDistanz: objektsprachlich \\n--> Begründung: mit der Einbildungskraft wird die Funktionsweise des Erinnerns beschrieben\\n\\nDisziplin: Psychologie\\n--> Begründung: es wird über Einbildungskraft im Zusammenhang mit dem Erinnern geschrieben \\n\\nQuelle der Bewertung: textimmanent\\n--> Begründung: es wurde kein Kontextwissen herangezogen\")\n')
	count = 0
	for index,row in newdf.iterrows():
		count += 1
		f.write('\tvar classSection = form.addPageBreakItem()\n')
		f.write('\t\t.setTitle(\"')
		f.write("["+str(count)+"/10] ")
		f.write(row['sentence'].replace('\"','\\"'))
		f.write('\\n(')
		f.write(row['url'])
		f.write(', Zeile ca. ')
		f.write(str(row['line']))
		f.write(')\")\n')

		f.write('\tvar choices = [\"positiv\", \"negativ\", \"neutral\",\"Ich weiß es nicht.\"];\n')
		f.write('\tform.addMultipleChoiceItem()\n')
		f.write('\t\t.setTitle(question1)\n')
		f.write('\t\t.setChoiceValues(choices)\n')
		f.write('\t\t.setRequired(true);\n')
		f.write('\n')

		f.write('\tvar choices = [\"produktiv\", \"reproduktiv\", \"beides\",\"trifft nicht zu\",\"Ich weiß es nicht.\"];\n')
		f.write('\tform.addMultipleChoiceItem()\n')
		f.write('\t\t.setTitle(question2)\n')
		f.write('\t\t.setChoiceValues(choices)\n')
		f.write('\t\t.setRequired(true);\n')
		f.write('\n')

		f.write('\tvar choices = [\"aktiv\", \"passiv\", \"beides\",\"trifft nicht zu\",\"Ich weiß es nicht.\"];\n')
		f.write('\tform.addMultipleChoiceItem()\n')
		f.write('\t\t.setTitle(question3)\n')
		f.write('\t\t.setChoiceValues(choices)\n')
		f.write('\t\t.setRequired(true);\n')
		f.write('\n')

		f.write('\tvar choices = [\"individuell\", \"einige\", \"allgemein\",\"individuell und einige\",\"einige und allgemein\",\"individuell und allgemein\",\"trifft nicht zu\",\"Ich weiß es nicht.\"];\n')
		f.write('\tform.addMultipleChoiceItem()\n')
		f.write('\t\t.setTitle(question4)\n')
		f.write('\t\t.setChoiceValues(choices)\n')
		f.write('\t\t.setRequired(true);\n')
		f.write('\n')

		f.write('\tvar choices = [\"direktes Zitat\", \"indirektes Zitat\", \"Titel\",\"Meinung\", \"andere Quelle und Meinung\", \"trifft nicht zu\",\"Ich weiß es nicht.\"];\n')
		f.write('\tform.addMultipleChoiceItem()\n')
		f.write('\t\t.setTitle(question5)\n')
		f.write('\t\t.setChoiceValues(choices)\n')
		f.write('\t\t.setRequired(true);\n')
		f.write('\n')

		f.write('\tvar choices = [\"objektsprachlich\", \"metasprachlich\", \"beides\", \"trifft nicht zu\",\"Ich weiß es nicht.\"];\n')
		f.write('\tform.addMultipleChoiceItem()\n')
		f.write('\t\t.setTitle(question6)\n')
		f.write('\t\t.setChoiceValues(choices)\n')
		f.write('\t\t.setRequired(true);\n')
		f.write('\n')

		f.write('\tvar item = form.addCheckboxItem();\n')
		f.write('\titem.setTitle(')
		f.write('question7')
		f.write(')\n')
		f.write('\t\t.setChoices([\n')
		f.write('\t\t\titem.createChoice(\'Ästhetik (Bildende Kunst, Literatur, Mythologie, Musik etc.)\'),\n')
		f.write('\t\t\titem.createChoice(\'Geschichte\'),\n')
		f.write('\t\t\titem.createChoice(\'Medizin\'),\n')
		f.write('\t\t\titem.createChoice(\'Naturwissenschaften (Biologie, Chemie, Geographie, Geologie etc.)\'),\n')
		f.write('\t\t\titem.createChoice(\'Pädagogik\'),\n')
		f.write('\t\t\titem.createChoice(\'Philosophie\'),\n')
		f.write('\t\t\titem.createChoice(\'Psychologie\'),\n')
		f.write('\t\t\titem.createChoice(\'Religion\'),\n')
		f.write('\t\t\titem.createChoice(\'andere\'),\n')
		f.write('\t\t])\n')
		f.write('\t\t.setRequired(true)\n')
		f.write('\t\t.showOtherOption(false);\n')

		f.write('\tvar item = form.addCheckboxItem();\n')
		f.write('\titem.setTitle(')
		f.write('question8')
		f.write(')\n')
		f.write('\t\t.setChoices([\n')
		f.write('\t\t\titem.createChoice(\'Ja\'),\n')
		f.write('\t\t])\n')
		f.write('\t\t.showOtherOption(false);\n')

		f.write('\tvar choices = [\"textimmanent\", \"kontextuell\", \"Ich weiß es nicht.\"];\n')
		f.write('\tform.addMultipleChoiceItem()\n')
		f.write('\t\t.setTitle(question9)\n')
		f.write('\t\t.setChoiceValues(choices)\n')
		f.write('\t\t.setRequired(true);\n')
		f.write('\n')

		f.write('\tvar item = form.addCheckboxItem();\n')
		f.write('\titem.setTitle(')
		f.write('question10')
		f.write(')\n')
		f.write('\t\t.setChoices([\n')
		f.write('\t\t\titem.createChoice(\'Ja\'),\n')
		f.write('\t\t])\n')
		f.write('\t\t.showOtherOption(false);\n')

	f.write('}')
